events {}
http {
    proxy_cache_path /cache keys_zone=mycache:10m;

    server {
        listen 80;

        location / {
            root /statics;
        }

        location /api/ {
            proxy_pass http://backend:3000/;
        }

        location /api/stats/ {
            proxy_pass http://backend:3000/stats;
            add_header X-Cache-Status $upstream_cache_status always;
            proxy_cache mycache;
            proxy_cache_valid any 30s;
        }       
    }
}