services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      INSTANCE_ID: "1"

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
    - ./nginx/statics:/statics
    depends_on:
      - backend
